### ISSUE TITLE
[FEATURE] JIRA task integration

### ISSUE THREAD

**Issue by zerodayz** [unofficial-memsource/memsource-cli-client#1]
**Is your feature request related to a problem? Please describe.**
For the purpose of Automation. It should be possible to create JIRA task from memsource CLI.

**Describe the solution you'd like**
I would like to be able to create task from memsource client like this:
```
memsource jira task create --jira-url <String> --summary <String> \
--components <Objects> --affects-versions <Objects> \
--fix-versions <Objects> --description <String> \
--original-estimate <String> --labels <List> --epic <String> \
--story-points <Int> --sprint <String>
```
**Describe alternatives you've considered**
Not available

**Additional context**
By default we use kerberos for authentication, `requests` with `negotiate` will be sufficient.

**Comment by ludekjanda** [comment]
Do we want the JIRA integration here? 

I would somehow prefer having a separate command to create and handle JIRA tickets. That JIRA command would read the values from “memsource project show” and pass them to JIRA. 

But I may be wrong.

**Comment by zerodayz** [comment]
Feature added in commit https://github.com/unofficial-memsource/memsource-cli-client/commit/35f874390bcf0dd878a67c769c64868514914c66
