### ISSUE TITLE
[FEATURE] Download multiple jobs at once as ZIP (mxliff)

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#10]
**Is your feature request related to a problem? Please describe.**
My understanding is that the current "memsource file download" downloads jobs one by one. 
However the standard way to download multiple files from Memsource is a bulk download in ZIP format at once. 

The reason is that if the translation project has some folder structure, the only way to preserve it is with ZIP file on upload to Memsource and on download. You basically select all jobs, after you click Download, they are compressed in ZIP and downloaded. 

Also a typical download scenario for the output bilingual MXLIFF format is to download multiple jobs at once so that they can be open at once in one Editor screen. 

**Describe the solution you'd like**
I'd like the parameter "job-id" to accept multiple values:

ex: memsource job file download --project-id SOMETHING --job-id ID,ID,ID,ID --type target

**Additional context**
Now getting this error on trying to pass multiple IDs: 

{"errorCode":"Invalid parameters","errorDescription":"Job \"1ItXs2W3pcRk1Q4CjB0SH7,o6bfVjyk2hXE39Y5zgXX33\" not imported correctly or import is in progress"}

**Comment by zerodayz** [comment]
As of now I am not aware of API that would allow such thing. I am using https://cloud.memsource.com/web/docs/api#operation/completedFile that only takes only one job uid.

**Comment by zerodayz** [comment]
If there is no API we could workaround this by downloading one-by-one and compress locally.

**Comment by zerodayz** [comment]
@ludekjanda 

Do you agree with this?

Reproducer:
1. Create a ZIP file:
```
 zip -r a.zip a/
  adding: a/ (stored 0%)
  adding: a/b.md (stored 0%)
  adding: a/c/ (stored 0%)
  adding: a/c/d.md (stored 0%)
```
Upload ZIP file to the memsource
```
memsource job create --project-id 3Bozqg0bJ0DJN4UZ8yh91p --filenames ~/a.zip --target-langs ja                                    
```

Download job from memsource
```
memsource job download --project-id 3Bozqg0bJ0DJN4UZ8yh91p --job-id WiZ2gQfZreo9ahEqNrWHm
```

Actual results:
File is saved as `a%2Fb-en-ja-C.md`

Expected results:
1. Create directory `a`
2. Create file `b-en-ja-C.md` in that directory

After we got this working, we can add multiple jobs downloads at once.

Or do you prefer to create ZIP file and save it as ZIP file?

**Comment by ludekjanda** [comment]
Agreed, @zerodayz this reproducer describes nicely the issue. Let's wait for Memsource if there is such API call now. I am afraid there must be some other way to get the original path from the downloaded document. In this project it's just a coincidence that it is in the filename because the File renaming options in this specific project include "path". See: "Rename completed files to: {path}/{fileName}_{targetLang}" there.

**Comment by zerodayz** [comment]
The download improved in https://github.com/unofficial-memsource/memsource-cli-client/commit/ce48bae272f390481fc878b26c810ba914f7197c
