### ISSUE TITLE
[FEATURE] Show template values

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#11]
**Is your feature request related to a problem? Please describe.**

I need a way to get defined values for a specific template. 

It happened to me that I created a project with "zh" while the supposed language meant to be "zh_cn". 

$ memsource project template create -f value -c uid --name "SOMETHING" --template-id SOMENUMBER --target-langs ja fr zh_cn

This API call gives that information: 
https://cloud.memsource.com/web/docs/api#operation/getProjectTemplate

**Describe the solution you'd like**

$ memsource project template show --template-id SOMENUMBER -f value -c targetLangs

**Describe alternatives you've considered**

**Additional context**

**Comment by zerodayz** [comment]
Assigning to @ludekjanda

**Comment by ludekjanda** [comment]
The feature has been added with this commit: https://github.com/unofficial-memsource/memsource-cli-client/commit/7bd00d1377e6a01d23f29641cb759f59430dc8ff 

Wiki link: https://github.com/unofficial-memsource/memsource-cli-client/wiki/Memsource-Template#template-show
