### ISSUE TITLE
[FEATURE] Rename memsource project template create to memsource project create

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#13]
**Is your feature request related to a problem? Please describe.**
"memsource project template create" is confusing, it looks like we are creating a template here. 
 
**Describe the solution you'd like**
"memsource project create" 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by zerodayz** [comment]
Agree with the change @ludekjanda  it should be easy one, but please note it will break the compatibility so the change should go towards `0.3.z` version

**Comment by ludekjanda** [comment]
Solved with 7b79b214412d7961b0686ea71e83b800dabe54ef.
