### ISSUE TITLE
[FEATURE] Add option to define memsource base url

### ISSUE THREAD

**Issue by jwestrmaier** [unofficial-memsource/memsource-cli-client#17]
**Describe the bug**
Unable to create job because of invalid projectUid even if the projectUid exists
memsource job create --filenames csv_example.csv virt-who.xml --project-id s0sRdE0aIvzxLQfhGUEU6e

**Affected version**
0.3.1

**To Reproduce**
memsource job create --filenames csv_example.csv virt-who.xml --project-id s0sRdE0aIvzxLQfhGUEU6e

**Expected behavior**
A job is created.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/58473784/70054556-15bc4280-15d8-11ea-8fbd-fab4cefa548f.png)

**Comment by ludekjanda** [comment]
Hi @jwestrmaier ,

you are reporting the issue for "memsource job create --filenames csv_example.csv virt-who.xml --project-id s0sRdE0aIvzxLQfhGUEU6e" 

When I run this command I get the following error: 
Starting new HTTPS connection (1): cloud.memsource.com
Memsource API Error
Error: InvalidArguments
Error description: The field "targetLangs" cannot be empty.
Response status: 400

Your command is missing the parameter "--target-langs", in your case it should be "--target-langs de"

**Comment by jwestrmaier** [comment]
The result is the same even if I use "--target-langs" param in request
![Image 2019-12-03 at 2 45 50 PM png](https://user-images.githubusercontent.com/58473784/70056427-ba8c4f00-15db-11ea-84ca-5b81832bc406.png)

**Comment by ludekjanda** [comment]
Is it only this specific project that gives you error?

**Comment by jwestrmaier** [comment]
The thing is when I use post request it does work.
This is raw request for create job operation via api :

```
POST https://qa.memsource.com/web/api2/v1/projects/s0sRdE0aIvzxLQfhGUEU6e/jobs?token=[CENSORED]

POST data:
--Fj3SxJv_5mA0WprCd-O9pRdiLoqTZLDcXfREFb
Content-Disposition: form-data; name=" csv"; filename="csv_example.csv"
Content-Type:  csv
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--Fj3SxJv_5mA0WprCd-O9pRdiLoqTZLDcXfREFb--


[no cookies]

Request Headers:
Connection: keep-alive
Memsource: { "targetLangs": [ "de" ] ,"useProjectFileImportSettings": "true"}
Content-Disposition: filename*=UTF-8''file.csv
Content-Type: application/octet-stream
Content-Length: 447
Host: qa.memsource.com
User-Agent: Apache-HttpClient/4.5.5 (Java/1.8.0_231)
```

**Comment by jwestrmaier** [comment]
> Is it only this specific project that gives you error?
> […](#)

I am going to try it on another project

**Comment by ludekjanda** [comment]
Can you also run the memsource cli command with „--debug“ parameter and send us the output?

L

**Comment by jwestrmaier** [comment]
jiri.westrmaier@jwestrmaiermac Downloads % **memsource job create --filenames csv_example.csv --project-id s0sRdE0aIvzxLQfhGUEU6e --target-langs de --debug**     
2019-12-03 14:57:15,780 DEBUG Starting new HTTPS connection (1): cloud.memsource.com:443
send: b"POST /web/api2/v1/projects/s0sRdE0aIvzxLQfhGUEU6e/jobs?token=[CENSORED]HTTP/1.1\r\nHost: cloud.memsource.com\r\nUser-Agent: python-requests/2.22.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Type: application/octet-stream\r\nContent-Disposition: filename=csv_example.csv\r\nMemsource: {'targetLangs': ['de'],'useProjectFileImportSettings': 'true'}\r\nContent-Length: 229\r\n\r\n"
sendIng a read()able
send: b'Second\r\nThird\r\nTEST 35\r\nChanged frquency\r\nContinuous job - frequency not changed\r\n? Export Continuous Job - Google Drive - One workflow step - Every 5 minutes\r\nAnother new translation file?\r\nPropagation in shared job\r\nAvalanche\r\n'
reply: 'HTTP/1.1 404 \r\n'
header: Memsource-Action-Id: d56695fae2a94390b60b2a38b51007f0
header: X-Frame-Options: DENY
header: Cache-Control: no-store, private, max-age=0
header: Expires: Tue, 03 Dec 2019 12:57:15 GMT
header: Last-Modified: Tue, 03 Dec 2019 13:57:15 GMT
header: Date: Tue, 03 Dec 2019 13:57:15 GMT
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Server: 
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
2019-12-03 14:57:15,928 DEBUG https://cloud.memsource.com:443 "POST /web/api2/v1/projects/s0sRdE0aIvzxLQfhGUEU6e/jobs?token=[CENSORED]
HTTP/1.1" 404 None
Memsource API Error
Error: Invalid parameters
Error description: The object referenced by the field "projectUid" and value "s0sRdE0aIvzxLQfhGUEU6e" was not found.
Response status: 404

**Comment by jwestrmaier** [comment]
I can see where is an issue >>> different site "https://cloud.memsource.com".  But I am logged in "https://qa.memsource.com"
`# Default Base url
  self.host = "https://qa.memsource.com/web"`

**Comment by jwestrmaier** [comment]
Is there any place where to define Base Url for `job creation` ??

**Comment by ludekjanda** [comment]
This is an interesting feature request at the end :-)  

I can see cloud.memsource.com defined in 2 places: 
utils.py 
API_URL = 'https://cloud.memsource.com/web/api2/‚

configuration.py
self.host = "https://cloud.memsource.com/web“ 

May be something worth working on.

**Comment by jwestrmaier** [comment]
Nice job. API_URL edited and now it does work :)

![Image 2019-12-03 at 3 35 13 PM png](https://user-images.githubusercontent.com/58473784/70060282-84060280-15e2-11ea-8a90-148013ecea7d.png)

I think the issue is resolved. 👍

**Comment by ludekjanda** [comment]
I am reopening this issue. We think it's a good idea to have a way to use custom API URLs. We'll work on this feature.

**Comment by zerodayz** [comment]
@jwestrmaier 

Command Line Option to use custom URL:
````
  --ms-auth-url <auth-url>
                        Authentication URL (Env: MEMSOURCE_URL)
````
or add to your memsourcerc file:
````
export MEMSOURCE_URL="https://cloud.memsource.com/web"
````

Added in https://github.com/unofficial-memsource/memsource-cli-client/commit/6eb8e4b1f9cabcf7135c89bed8b414c8b83ff1bb
