### ISSUE TITLE
[BUG] Token should be hidden in debug logs

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#18]
**Describe the bug**
--debug option generates a log that contains token

**Affected version**
All

**To Reproduce**
Run any command with --debug option . There is a line with the API call and "token=". 

**Expected behavior**
Token should be hidden. 

**Screenshots or Traceback**
n/a

**Additional context**
n/a

**Comment by zerodayz** [comment]
Added in https://github.com/unofficial-memsource/memsource-cli-client/commit/b5c66e933f3c922d68a8cf39da6338065ead51f7
