### ISSUE TITLE
[BUG][0.3.1] memsource job create --debug has empty output

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#20]
**Describe the bug**

memsource job create --debug has empty output

**Affected version**
<0.3.1

**To Reproduce**
$ memsource job create --debug

Result: nothing

**Expected behavior**
A log should be displayed. 

**Screenshots or Traceback**
n/a

**Additional context**
n/a

**Comment by zerodayz** [comment]
https://github.com/unofficial-memsource/memsource-cli-client/commit/59a9d27a64482ab700519987c159794a8159f115
