### ISSUE TITLE
[FEATURE] Multiple job support for "memsource job edit" command

### ISSUE THREAD

**Issue by mehmetpisirici** [unofficial-memsource/memsource-cli-client#21]
According to the wiki page, some commands (such as "memsource job download") support using multiple job ids or an argument that list all job ids but "memsource job edit" command doesn't support this. For example this command runs successfully:

`memsource job download --project-id <PROJECTID>--output-dir output --job-id $(memsource job list --project-id <PROJECTID> -f value -c uid | tr '\n' ' ')`

But this command fails:

`memsource job edit --status ACCEPTED --project-id <PROJECTID> --job-id $(memsource job list --project-id <PROJECTID> -f value -c uid | tr '\n' ' ')`

This one fails too:

`memsource job edit --status ACCEPTED --project-id <PROJECTID> --job-id <JOBID> <JOBID> <JOBID> <JOBID> <JOBID>`

The error is:

`memsource job edit: error: unrecognized arguments: <list of job ids in the project, all jobs except the first one, I believe this is because the command only accepts one argument>`

What I need to do is to change the status of all jobs in a specific project where I know the project id but not the job ids. If there is a workaround for this, I would be happy to hear but I don't have deep knowledge in coding so please keep it simple. I am tagging you, @ludekjanda since Robin said you would be able to look into this one.

Many thanks in advance!

**Comment by ludekjanda** [comment]
Hi @mehmetpisirici  the following script should do the job: 

```
#!/bin/bash

PROJECT="06dWLpq2e0zy8kJDE0ARQ4" #Change to your Project ID
STATUS="ACCEPTED"
JOBS=($(memsource job list --project-id $PROJECT -f value -c uid | tr '\n' ' '))
for JOB in "${JOBS[@]}"; do
  memsource job edit --status $STATUS --project-id $PROJECT --job-id $JOB
echo "Job $JOB changed the status to $STATUS"
done

echo "Done"
```

I've tested it and it worked in my case. Let me know if the script worked.

**Comment by mehmetpisirici** [comment]
Thank you @ludekjanda The script worked great and will do the job.

Is it also possible to change the job status according to the original job status? For example if a job's status is NEW, change it to ACCEPTED but else, leave as is.

Also, as a newbie question, how to make this work at intervals, like every 10 minutes?

**Comment by ludekjanda** [comment]
@mehmetpisirici  here is the version which is checking the current status: 
```
#!/bin/bash

PROJECT="06dWLpq2e0zy8kJDE0ARQ4" #Change to your Project ID
STATUS="EMAILED"
JOBS=($(memsource job list --project-id $PROJECT -f value -c uid | tr '\n' ' '))
for JOB in "${JOBS[@]}"; do
  CURRENT_STATUS=$(memsource job show --project-id $PROJECT --job-id $JOB -f value -c status)
  echo "Current status is $CURRENT_STATUS"
  if [ $CURRENT_STATUS != $STATUS ]; then
    memsource job edit --status $STATUS --project-id $PROJECT --job-id $JOB
    echo "Job $JOB changed the status from $CURRENT_STATUS to $STATUS"
  else
    echo "No status change needed"
  fi
done

echo "Done"


```

To run it in intervals, you probably need to set up a "cron job" in your machine which would be running this script in desired intervals. Google for "cron job" if you are on Macos or Linux. Not sure how it works in Win.

**Comment by ludekjanda** [comment]
Sorry @mehmetpisirici there was a small problem in my previous scripts, I had to update them slightly. More specifically the change was in this:     memsource job edit --status $STATUS --project-id $PROJECT --job-id $JOB

**Comment by mehmetpisirici** [comment]
Many thanks @ludekjanda I will take this from here and keep on experimenting. I will also be keeping an eye on the project updates.

**Comment by ludekjanda** [comment]
@mehmetpisirici nps, feel free to experiment, this is a powerful tool especially where you need to process large numbers of source files periodically. Once you have your script written, it becomes a huge time saver.

**Comment by zerodayz** [comment]
Re-opening as we will be implementing this feature in future.

**Comment by zerodayz** [comment]
Agreed to do a extra CLI option: jobs edit 

`    jobs_edit = memsource_cli.job.v1.job:EditJobs`

**Comment by zerodayz** [comment]
Added in https://github.com/unofficial-memsource/memsource-cli-client/commit/201a4273018affbd440fe372cd5a4e8e60ac8eeb

Now you can do something like:

```
(.memsource) [rcernin@localhost memsource-cli-client]$ memsource jobs edit --project-id Yh6jYmsPNLVW4JC9WlpCJ0 --status COMPLETED --jobs bbuEGzhDngaD3NqKIoG3r0 rr2Vykywuq8D6d10vHmFs2
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field | Value                                                                                                                                                                                                   |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| jobs  | [{'uid': 'bbuEGzhDngaD3NqKIoG3r0', 'status': 'COMPLETED', 'providers': [], 'target_lang': 'ja', 'workflow_level': 1, 'workflow_step': None, 'filename': 'test.md', 'date_due': None, 'date_created':    |
|       | datetime.datetime(2020, 3, 27, 7, 10, 28, tzinfo=tzutc()), 'imported': True, 'job_assigned_email_template': None, 'notification_interval_in_minutes': -1, 'continuous': False}, {'uid':                 |
|       | 'rr2Vykywuq8D6d10vHmFs2', 'status': 'COMPLETED', 'providers': [], 'target_lang': 'ja', 'workflow_level': 1, 'workflow_step': None, 'filename': 'test.md', 'date_due': None, 'date_created':             |
|       | datetime.datetime(2020, 3, 27, 8, 26, 35, tzinfo=tzutc()), 'imported': True, 'job_assigned_email_template': None, 'notification_interval_in_minutes': -1, 'continuous': False}]                         |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
(.memsource) [rcernin@localhost memsource-cli-client]$ memsource job list --project-id Yh6jYmsPNLVW4JC9WlpCJ0
+------------------------+-----------+-----------+-------------+---------------+----------+----------+---------------------------+----------+------------+
| uid                    | status    | providers | target_lang | workflow_step | filename | date_due | date_created              | imported | continuous |
+------------------------+-----------+-----------+-------------+---------------+----------+----------+---------------------------+----------+------------+
| bbuEGzhDngaD3NqKIoG3r0 | COMPLETED | []        | ja          | None          | test.md  | null     | 2020-03-27 07:10:28+00:00 | True     | False      |
| rr2Vykywuq8D6d10vHmFs2 | COMPLETED | []        | ja          | None          | test.md  | null     | 2020-03-27 08:26:35+00:00 | True     | False      |
+------------------------+-----------+-----------+-------------+---------------+----------+----------+---------------------------+----------+------------+
```
