### ISSUE TITLE
[BUG] Job download does not display info about required arguments

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#23]
**Describe the bug**
"$ memsource job download" does not display info about missing arguments but gives a valid result

**Affected version**
Alll 

**To Reproduce**
$ memsource job download
+--------+----------+
| Field  | Value    |
+--------+----------+
| type   | target   |
| format | ORIGINAL |
| path   | []       |
+--------+----------+

**Expected behavior**

Usage + error with required arguments 

Something like: 
usage: memsource user get [-h] [-f {json,shell,table,value,yaml}] [-c COLUMN]
                          [--noindent] [--max-width <integer>] [--fit-width]
                          [--print-empty] [--prefix PREFIX] --user-id USER_ID
memsource user get: error: the following arguments are required: --user-id

**Comment by zerodayz** [comment]
https://github.com/unofficial-memsource/memsource-cli-client/commit/12a8cc02da39ed90d3be48eee6b290ddb75b4aac
