### ISSUE TITLE
[FEATURE] Display total page counts in a job list

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#26]
**Is your feature request related to a problem? Please describe.**
We need to have a way to display total page counts when working with larger projects. Use case is explained in this bug report: https://github.com/unofficial-memsource/memsource-cli-client/issues/25 

**Describe the solution you'd like**
memsource job list --project-id tCQYoSuMvoUxatSpkj0On3 --target-lang 'ja' -f value -c totalPages 

**Describe alternatives you've considered**
We used a workaround bash script to reiterate through all jobs. Details in https://github.com/unofficial-memsource/memsource-cli-client/issues/25  

**Additional context**
n/a

**Comment by zerodayz** [comment]
Added in 0.3.8

```
memsource job list --project-id 9iFwa1rk54RL3WWSi9hVf5 -f value -c total_elements -c total_pages -c page_size -c page_number -c number_of_elements

1 1 50 0 1
```
This is hidden from the output unless you specifically access with `-c`
