### ISSUE TITLE
[BUG] 0.2.4 -- setup.py fails due to mismatch in package name/version

### ISSUE THREAD

**Issue by rh-rlandman** [unofficial-memsource/memsource-cli-client#4]
**Describe the bug**
setup.py fails due to mismatch in package name/version

**Affected version**
0.2.4

**To Reproduce**
Run: 
python3 setup.py build '--executable=/usr/bin/python3 -s'

**Expected behavior**
setup.py succeeds and framework builds

**Screenshots or Traceback**

/usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
/usr/lib/python3.6/site-packages/setuptools/dist.py:47: DistDeprecationWarning: Do not call this function
  warnings.warn("Do not call this function", DistDeprecationWarning)
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.6/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3.6/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name memsource_cli was given, but was not able to be found.
error in setup command: Error parsing memsource-cli-client-0.2.4/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name memsource_cli was given, but was not able to be found.

**Additional context**

**Comment by zerodayz** [comment]
@rh-rlandman 
Pbr will first try to get the version from PKG-INFO or METADATA files (generated from setup.py), if it exists.
If it does, then that means we're in a distribution tarball or that install has happened.

If it doesn't exist the Pbr will try to pull the version from git.

Now the error is that says, basically:
- Could not find PKG-INFO or METADATA
- Do not have access to git to get the version from.

#### For PyPI installation:
Version is extracted from PKG_INFO file. PKG_INFO is created during the upload process to PyPI:
```
dpl.3
Deploying application
running sdist
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running egg_info
creating memsource_cli.egg-info
writing requirements to memsource_cli.egg-info/requires.txt
writing memsource_cli.egg-info/PKG-INFO
```

#### For Github
Version is extracted from git tags automatically, please check if your repository is cloned with tags.

**Comment by zerodayz** [comment]
Check if PKG_INFO exists if you used PyPI.

**Comment by zerodayz** [comment]
@rh-rlandman 

I see where the problem is:

When you download the source code from the website. It doesn't have the PKG_INFO because its not built for PyPI, and it also doesn't have the git tags, as it was not cloned.

Now the reason for this I opted out of specify the version in the code, instead is being built from the git tags during the push.

This removes the manual work on setting the release in the code. I will take a look how it can be solved. However tagging as low because it should not be problem for anyone who is using PyPI or Github clones.

**Comment by rh-rlandman** [comment]
Thanks! It would also solve this for me if:

* there was a way to pass this info on the command line when running setup.py

Or

* I can generate PKG_INFO from the command line at build time

-- I'll investigate both these possibilities as well

**Comment by zerodayz** [comment]
@rh-rlandman 
You can build the application by exporting the version string manually:
`export PBR_VERSION=0.2.4`

**Comment by rh-rlandman** [comment]
Thanks! I just tried that; I still get a similar error; then I found that although the error report says:

Project name **memsource_cli** was given, but was not able to be found.

but the PKG-INFO contains

Metadata-Version: 2.1
Name: **memsource-cli**
Version: 0.2.4

Going to delve a little more here...

**Comment by zerodayz** [comment]
@rh-rlandman  

I see where the problem is here. Try changing `setup.cfg`
```
[metadata]
name = memsource_cli
```
to
```
[metadata]
name = memsource-cli
```

**Comment by zerodayz** [comment]
It's fixed in this commit now https://github.com/unofficial-memsource/memsource-cli-client/commit/f68624062b78724a89d6f49efce919a171fd5185

**Comment by zerodayz** [comment]
@rh-rlandman 
Looking into `/usr/lib/python3.7/site-packages/pbr/packaging.py`
There is no other way to determine the version than `git tag` or `PKG-INFO` or explicitly set `PBR_VERSION`

See:

```
def get_version(package_name, pre_version=None):
    """Get the version of the project.

    First, try getting it from PKG-INFO or METADATA, if it exists. If it does,
    that means we're in a distribution tarball or that install has happened.
    Otherwise, if there is no PKG-INFO or METADATA file, pull the version
    from git.

    We do not support setup.py version sanity in git archive tarballs, nor do
    we support packagers directly sucking our git repo into theirs. We expect
    that a source tarball be made from our git repo - or that if someone wants
    to make a source tarball from a fork of our repo with additional tags in it
    that they understand and desire the results of doing that.

    :param pre_version: The version field from setup.cfg - if set then this
        version will be the next release.
    """
    print("PBR_VERSION is set to %s" % os.environ.get("PBR_VERSION"))
    version = os.environ.get(
        "PBR_VERSION",
        os.environ.get("OSLO_PACKAGE_VERSION", None))
    if version:
        return version
    print("Trying PKG-INFO")
    version = _get_version_from_pkg_metadata(package_name)
    if version:
        return version
    version = _get_version_from_git(pre_version)
    # Handle http://bugs.python.org/issue11638
    # version will either be an empty unicode string or a valid
    # unicode version string, but either way it's unicode and needs to
    # be encoded.
    if sys.version_info[0] == 2:
        version = version.encode('utf-8')
    if version:
        return version
    raise Exception("Versioning for this project requires either an sdist"
                    " tarball, or access to an upstream git repository."
                    " It's also possible that there is a mismatch between"
                    " the package name in setup.cfg and the argument given"
                    " to pbr.version.VersionInfo. Project name {name} was"
                    " given, but was not able to be found.".format(
                        name=package_name))

```

Meaning if you don't use `git` or `pypi`, you should be able to set `PBR_VERSION` on `0.2.5` it works fine. 

I tried following and it worked on version `0.2.5`:
```
[memsource-cli-client-0.2.5]$ python3 setup.py build
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.7/site-packages/pbr/util.py", line 270, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3.7/site-packages/pbr/packaging.py", line 882, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name memsource-cli was given, but was not able to be found.
error in setup command: Error parsing /git/memsource-cli-client-0.2.5/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name memsource-cli was given, but was not able to be found.
[memsource-cli-client-0.2.5]$ 
[memsource-cli-client-0.2.5]$ export PBR_VERSION=0.2.5
[memsource-cli-client-0.2.5]$ python3 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/memsource_cli
```

if it doesn't work for you, please can you provide exact steps to reproduce with exporting `PBR_VERSION`

Please try reproducing it by and if you can send another Traceback you are getting with `PBR_VERSION` set.
```
wget https://github.com/unofficial-memsource/memsource-cli-client/archive/0.2.5.tar.gz
tar -xf 0.2.5.tar.gz
cd memsource-cli-client-0.2.5
export PBR_VERSION=0.2.5
python3 setup.py build
```

**Comment by rh-rlandman** [comment]
Thanks! That got me most of the way there. I'm doing this in an RPM buildroot; to solve it I needed to:

1. use the "-S git" switch for the %autosetup macro
2. set the PBR_VERSION in both the %build *and* %install stages. 

i.e.:

----

%prep
%autosetup -n memsource-cli-client-%{version} -S git

%build
export PBR_VERSION=%{version} 
%py3_build

%install
export PBR_VERSION=%{version} 
%py3_install

%check
%{__python3} setup.py test

----
 Builds perfectly now! Thanks!
