### ISSUE TITLE
[FEATURE] Pre-translation

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#8]
**Is your feature request related to a problem? Please describe.**
Currently the only way to pre-translate the project is on job creation. But there is no way to pretranslate existing jobs. 

**Additional context**
Similar to https://cloud.memsource.com/web/docs/api#operation/preTranslate

**Comment by zerodayz** [comment]
@ludekjanda  Added in master, next 0.2.9 release.

https://github.com/unofficial-memsource/memsource-cli-client/wiki/Memsource-Translation
